import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'secondary-fixed-dim': '#bfdad4',
        'surface-bright': '#f8f9fb',
        'inverse-primary': '#b4fcee',
        'surface-variant': '#dee3e7',
        'inverse-on-surface': '#9b9d9f',
        'on-primary': '#e2fff8',
        'on-secondary': '#e3fff8',
        'tertiary-fixed-dim': '#a4d6eb',
        'secondary-dim': '#3f5853',
        'on-error': '#fff7f6',
        'surface-dim': '#d5dbdf',
        'primary-dim': '#0b5e54',
        'on-tertiary-fixed-variant': '#2b5e70',
        'on-primary-fixed': '#004840',
        'surface-container': '#ebeef1',
        'on-primary-fixed-variant': '#1a665c',
        'on-tertiary-container': '#205466',
        'surface': '#f8f9fb',
        'on-background': '#2d3337',
        'primary-fixed-dim': '#9be2d5',
        'on-secondary-container': '#3e5752',
        'primary': '#1f6a60',
        'surface-container-highest': '#dee3e7',
        'background': '#f8f9fb',
        'secondary-fixed': '#cce8e2',
        'error': '#a83836',
        'tertiary': '#336577',
        'on-surface': '#2d3337',
        'inverse-surface': '#0c0f10',
        'secondary': '#4b645f',
        'on-secondary-fixed-variant': '#47605b',
        'primary-container': '#a9f0e3',
        'surface-container-high': '#e4e9ec',
        'surface-container-low': '#f1f4f7',
        'on-tertiary': '#f2faff',
        'on-tertiary-fixed': '#024153',
        'outline-variant': '#adb3b7',
        'surface-tint': '#1f6a60',
        'outline': '#767b7f',
        'error-container': '#fa746f',
        'tertiary-container': '#b2e4fa',
        'on-error-container': '#6e0a12',
        'error-dim': '#67040d',
        'secondary-container': '#cce8e2',
        'primary-fixed': '#a9f0e3',
        'on-secondary-fixed': '#2b443f',
        'tertiary-fixed': '#b2e4fa',
        'tertiary-dim': '#25596b',
        'on-surface-variant': '#5a6064',
        'on-primary-container': '#085c53',
        'surface-container-lowest': '#ffffff',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
      fontFamily: {
        'headline': ['Manrope', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}

export default config
